fragment UniqueLayoutQueryFragment on Query {
  global(relativePath: "index.json") {
    ... on Global {
      header {
        name
        color
        nav {
          href
          label
        }
      }
      theme {
        color
        font
        darkMode
      }
    }
  }
}