query pageQuery {
  ...UniqueLayoutQueryFragment
  postConnection {
    edges {
      node {
        id
        date
        title
        excerpt
        _sys {
          filename
        }
      }
    }
  }
}

query blogPostQuery($relativePath: String!) {
  post(relativePath: $relativePath) {
    id
    title
    date
  }
}